### ISSUE TITLE
Log & status rest api

### ISSUE THREAD

**Issue by alfem** [gecos-team/gecoscc-ui#22]
GECOS CC is a complex deployment. If we had a couple of methods to check last lines of webui log and server connection status, diagnostics would be much easier.

Bear in mind these api calls will be served (in production environments) by a central load balancer, and answer served by any frontend server. 

Suggested urls:
/server/log?lines=100       retrieves latest 100 lines of webui logs
/server/connections          retrieves a parseable list of server connection status (chef, celery)
/server/status                    retrieves a parseable list of monitoring data (disk space, memory, cpu usage)

These urls should be available to authenticated superusers only

**Comment by System25** [comment]
Hi, I think that this could be done by maintaining a list of GECOS CC servers in the database. For example, we could save a name and the IP address of the servers. 

When a new GECOS CC server is added it would add automatically it's IP address to the list. But if a server is removed the administrator must remove manually the server from the list.

Given that server list, we could show the status of the servers by following these steps:
1) The administrator user access to the log main web page (/server/log?lines=100)
2) That particular GECOS CC server access internally to the other GECOS CC internal log page (/server/internal_log=lines=100) and aggregates the result.
3) The admistrator user views an aggregated web page with the different logs.

![logs gecos](https://cloud.githubusercontent.com/assets/4385829/9109950/0e4e5dca-3c3a-11e5-9ed6-b59b7d838b0f.png)

The **status of the server** could have a different solution. Knowing the memory and CPU usage in a specific moment is not specially useful. So maybe it's better to create a thread that stores in the database information about the CPU and memory usage each 30 seconds.

With that data we could display a graph that shows the memory usage between a time interval. For example the last our.

What do you think about this solutions?

**Comment by alfem** [comment]
Your log aggregation solution seems perfect to me.

About the status, I would rather prefer not to saturate the database with this data.  Perhaps we will enhance this status api in a future, but right now a simple solution is preferable.

**Comment by System25** [comment]
I've realized that there are different processes in each GECOS CC server controlled by a "supervisor". So there are two (or more) logs inside "/opt/gecosccui-2.1.9/supervisor/log/"

After that, checking de documentation of "supervisor", I've noticed that I can obtain information from the "supervisor" if we change the configuration:
  http://supervisord.org/configuration.html

So, instead of using:
  [unix_http_server]
  file=/opt/gecosccui-2.1.9/supervisor/run/supervisor.sock

we can use:
  [inet_http_server]
  port = 0.0.0.0:9001
  username = user
  password = 123

And instead of:
* /server/log?lines=100
* /server/internal_log?lines=100

we could use:
* /server/log?server=<server_name>&process=<proces_name>&bytes=10000 

Then the GECOSCC server would connect to the "supervisor" running in the desired server and obtain the last 10000 bytes of the log of that process.

To make this more usable, we could use the URL: "/server/log?server=<server_name>" as a first step by showing to the user a HTML table with the name and status of the processes.

NAVIGATION EXAMPLE:
1)  /server/status: Shows a HTML table with the servers in the cluster and the status of each server (CPU and RAM usage). The user clicks in the "log" button of the desired server.
2)  /server/log?server=<server_name>: Shows a HTML table with the name and status of the processes running on that server. The user selects a number of bytes from a list {5000, 10000 (default), 15000, 20000) and clicks in the "log" button of the desired process.
3) /server/log?server=<server_name>&process=<proces_name>&bytes=10000: Shows last 10.000 bytes of the log of that process in that server.

What do you think about this solution?

**Comment by alfem** [comment]
Some urls in views/server.py have 'http' schema hardcoded. 
This feature fails in production, with a "https" deployment.

**Comment by System25** [comment]
Pull request created for this issue. Please considerate it.

Thanks
